### ISSUE TITLE
msrest.exceptions.ValidationError: Parameter 'resource_group_name' must have length less than 90.

### ISSUE THREAD

**Issue by amitdimpy** [NetApp/ntaphana#11]
./ntaphana_azure.py --create-snapshot --cloud-volumes saps4--snapshot-name hanabkp27au --SID xx--key-file /home/xx/NetApp_HANA/ntaphana/key.json --config-file /home/xx/NetApp_HANA/ntaphana/config.json
file_system_id is not a known attribute of class <class 'azure.mgmt.netapp.models._models_py3.Snapshot'> and will be ignored
Traceback (most recent call last):
  File "./ntaphana_azure.py", line 940, in <module>
    auth, client_id, args.verbose)
  File "./ntaphana_azure.py", line 550, in create_snapshot
    credentials, snapshot_name, verbose)
  File "./ntaphana_azure.py", line 518, in create_snapshot_internal
    snapshot_name).result()
  File "/usr/local/lib64/python3.6/site-packages/azure/mgmt/netapp/operations/_snapshots_operations.py", line 291, in create
    **operation_config
  File "/usr/local/lib64/python3.6/site-packages/azure/mgmt/netapp/operations/_snapshots_operations.py", line 205, in _create_initial
    'resourceGroupName': self._serialize.url("resource_group_name", resource_group_name, 'str', max_length=90, min_length=1, pattern=r'^[-\w\._\(\)]+$'),
  File "/usr/local/lib/python3.6/site-packages/msrest/serialization.py", line 648, in url
    data = self._http_component_validation(data, data_type, name, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/msrest/serialization.py", line 636, in _http_component_validation
    data = self.validate(data, name, required=True, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/msrest/serialization.py", line 740, in validate
    raise ValidationError(key, name, value)
msrest.exceptions.ValidationError: Parameter 'resource_group_name' must have length less than 90.

**Comment by jimholl** [comment]
Thank you for reporting this issue. I have reproduced it and am investigating.

**Comment by amitdimpy** [comment]
Any update on it, as I was trying to use it for some testing.

**Comment by jimholl** [comment]
It appears to be an issue with the python3 version of the SDK. I can't be sure without identifying the change which broke it. The owners have been contacted. 

This particular command works with the python2 SDK, if you need a workaround right now.

**Comment by amitdimpy** [comment]
I installed python2, its pip and as per requirements all modules are installed:-
azure-common (1.1.25)
azure-mgmt-netapp (0.12.0)
azure-mgmt-nspkg (3.0.2)
azure-mgmt-resource (10.2.0)
azure-mgmt-subscription (0.6.0)
azure-nspkg (3.0.2)
msrestazure (0.6.4)
But the script is failing with this error:-
Error - expected libraries not found, see installation instructions
Traceback (most recent call last):
  File "./ntaphana_azure.py", line 92, in <module>
    sys.exit(2)
NameError: name 'sys' is not defined

Any idea what needs to be checked and what is remaining?

**Comment by amitdimpy** [comment]
Issue resolved, Thanks Jim for your support.
